name: Build and Publish Docker Image

on:
  push:
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image for PR
      uses: docker/build-push-action@v6
      with:
        context: .
        tags: |
          ghcr.io/${{ github.repository }}/openeducationarchive:${{ github.sha }}
        push: false

  build_release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        tags: |
          ghcr.io/${{ github.repository }}/openeducationarchive:${{ github.ref_name }}
        push: true

    - name: Log out from GitHub Container Registry
      run: docker logout ghcr.io


